### ISSUE TITLE
SO_REUSEPORT很早就被加入到php.ext.sockets里面了，和系统有关

### ISSUE THREAD

**Issue by joostshao** [walkor/workerman-manual#1]
https://github.com/php/php-src/blob/PHP-5.4/ext/sockets/sockets.c#L855

http://doc3.workerman.net/worker-development/listen.html

**Comment by walkor** [comment]
workerman用的是stream_socket，php7以前并不能设置stream_socket的SO_REUSEPORT选项

**Comment by joostshao** [comment]
http://php.net/manual/en/sockets.constants.php
