### ISSUE TITLE
Handle http request from curl (for example).

### ISSUE THREAD

**Issue by SprayDev** [walkor/workerman-manual#6]
Hello, I'm trying to understand WebSocket technology and I don't understand clearly how to handle requests from php server. 
For example:
I have 3 parts of my application
FrontEnd WebSite (JS)
Backend server(PHP)
WebSocket server (WorkerMan)

How can I from "Backend server" toggle some event on WebSocket server and send it to FrontEnd

**Comment by walkor** [comment]
```php
<?php
require_once __DIR__ . '/Workerman/Autoloader.php';
use Workerman\Worker;

$app_work = new Worker("websocket://0.0.0.0:8000");

$app_work->onWorkerStart = function ($worker) {
    $inner_worker = new Worker("websocket://0.0.0.0:1234");

    $inner_worker->onMessage = function ($connection, $request) use ($worker){
        foreach($worker->connection  as $con) {
            $con->send($request->get('somedata'));
        }
    };
    $inner_worker->listen();
};

$app_work->onMessage = function ($connection, $data) {
    echo "app_work=>".$data."\n";
};

$app_work->runAll();
```

FrontEnd WebSite.
```js
var ws = new WebSocket("ws://127.0.0.1:1234");
ws.onmessage = function(e){console.log(e.data);};
```

When Backend server visit url `http://domain.com:1234?somedata=blablabla....` by curl.
All FrontEnd page will receive data `blablabla....` by websocket.

More information see 
https://github.com/walkor/Workerman/issues/338 
https://github.com/walkor/Workerman/issues/184
https://github.com/walkor/Workerman/issues/175
https://github.com/walkor/Workerman/issues/169

**Comment by SprayDev** [comment]
Ohh, thank you very much :)
